album/urls.py
from django.urls import path, include
from album import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('category_rest', views.CategoryViewSet)
router.register('photo_rest', views.PhotoViewSet)




urlpatterns = [
    path('api/', include(router.urls)),
    path('',views.first_view,name='base'),
    path('category/',views.category, name='category-list'),
    path('category/<int:category_id>/detail/',views.category_detail,name='category-detail'),
    path('photo/',views.PhotoListView.as_view(),name='photo-list'),
    path('photo/<int:pk>/detail/',views.PhotoDetailView.as_view(),name='photo-detail'),
    # Update
    path('photo/<int:pk>/update/',views.PhotoUpdate.as_view(),name='photo-update'), 
    #Create
    path('photo/create/', views.PhotoCreate.as_view(), name='photo-create'),
    #Delete
    path('photo/<int:pk>/delete/', views.PhotoDelete.as_view(), name='photo-delete'),
    # Update
    path('category/<int:pk>/update/',views.CategoryUpdate.as_view(),name='category-update'), 
    #Create
    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    #Delete
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category-delete'),

]

myapp3/urls.py
from django.contrib import admin
from django.urls import path, include
from album import views

urlpatterns = [
    path('album/',include('album.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')),
    #path('accounts/', include('registration.backends.admin_approval.urls')),
    path('accounts/profile/',views.first_view),
    
    
]

album/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    """ Categorias para clasificar las fotos """
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category-list')

class Photo(models.Model):
    """ Fotos del Album """
    category = models.ForeignKey('Category', on_delete=models.PROTECT )
    title = models.CharField(max_length=50, default='No title')
    photo = models.ImageField(upload_to='photos/')
    pub_date = models.DateField(auto_now_add=True)
    favorite = models.BooleanField(default=False)
    comment = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo-list')

@receiver(post_delete, sender=Photo)
def photo_delete(sender, instance, **kwargs):
    """ Borra los ficheros de las fotos que se eliminan. """
    instance.photo.delete(False)

album/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from album.models import Category, Photo
from django.urls import reverse_lazy 
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from rest_framework import viewsets
from .serializers import CategorySerializer, PhotoSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class PhotoViewSet(viewsets.ModelViewSet):
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer


# Create your views here.
@login_required
def first_view(request):
    #return HttpResponse("<H1>HOLA MUNDO DESDE LA VISTA first_view</H1>")
    return render(request, 'base.html')

@login_required
def category(request):
    category_list = Category.objects.all()
    context = {'object_list': category_list}
    return render(request, 'album/category.html', context)

@login_required
def category_detail(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'object': category}
    return render(request, 'album/category_detail.html', context)
    
@method_decorator(login_required, name='dispatch')
class PhotoListView(ListView):
    model = Photo

@method_decorator(login_required, name='dispatch')
class PhotoDetailView(DetailView):
    model = Photo

class PhotoUpdate(UpdateView):
    model = Photo
    fields = '__all__' 

class PhotoCreate(CreateView):
    model = Photo
    fields = '__all__'

class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('photo-list')

class CategoryUpdate(UpdateView):
    model = Category
    fields = '__all__' 

class CategoryCreate(CreateView):
    model = Category
    fields = '__all__'

class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('category-list')

album/templates/album/category.html
{% extends 'base.html' %}

{% block section %}
 <h2>Category</h2>
 <hr>
{% endblock section %}

{% block maincontent %}
   <div>
      {% for c in object_list %}
         <a href="{% url 'category-detail' c.pk %}">
              {{ c.name }}
         </a>
      {% endfor %}
 </div>
{% endblock maincontent %} 

album/templates/album/category_detail.html
{% extends 'base.html' %}
 
{% load static %}

{% block section %}
    <h2>{{ object.name }}</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
  <div>
     <table border="1px">
      <tr>
          {% for p in object.photo_set.all %}
             <td>
               <div>{{ p.title }}</div>
               <div>
                  <a href="{% url "photo-detail" p.id %}">
                     <img src="{% static p.photo.url %}" style="width:200px;height:200px"/>
                  </a>
               </div>
             </td>
           {% endfor %}
       </tr> 
      </table>
   </div>
{% endblock maincontent %} 

album/templates/album/category_form.html
{% extends "base.html" %}

{% block maincontent %}
  <form enctype="multipart/form-data" method="post">{% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a class="btn" href="{% url 'category-list' %}">Cancel</a>
  </form>
{% endblock maincontent%} 

album/templates/album/photo_confirm_delete.html
{% extends 'base.html' %} 
{% block maincontent %}
 <form action=""method="post">{% csrf_token %}
 <p>Delete "{{ object.title }}"?</p>
 <input type="submit" value="Confirm" />
 <a class='btn'href="{% url 'photo-list' %}">Cancel</a>
 </form>
{% endblock maincontent %}

album/templates/album/photo_detail.html
{% extends 'base.html' %}

{% load static %}

{% block section %}
   <h2>
       {{ object.title }}
       {% if object.favorite %}
              &#9733;
       {% else %}
              &#9734;
       {% endif %}
       {% if object.category_id %}
         ( <a href="{% url "category-detail" object.category_id %}">
             {{ object.category }}
           </a> )
       {% endif %}
    </h2>
    <p><strong>comments: </strong>{{ object.comment|default:"no comments" }}</p>
    <a href="{% url "photo-update" object.id %}">edit</a>
    <a href="{% url "photo-delete" object.id %}">delete</a> 
   <hr>
{% endblock section %}

{% block maincontent %}
<div>
 <div>
     <img src="{% static object.photo.url %}" style="width:550px;height:420px" />
 </div>
</div>
{% endblock maincontent %} 

album/templates/album/photo_form.html
{% extends "base.html" %}


{% block maincontent %}
  <form enctype="multipart/form-data" method="post">{% csrf_token %}
    <div class="col-sm-6 ">
        {{ form.as_p }}
 
    <button type="submit">Save</button>
    <a class='btn' href="{% url 'photo-list' %}">Cancel</a>
  </div> 
  </form>
{% endblock maincontent%} 

album/templates/album/photo_list.html
{% extends 'base.html' %}

{% load static %}

{% block section %}
    <h2>Photo</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
    <div class="row well">
        {% for p in object_list.all %}
            <div class="col-md-4 well">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ p.title }}</h3>
                    </div>
                    <div class="panel-body">
                        <a href="{% url "photo-detail" p.id %}">
                            <img src="{% static p.photo.url %}" style="width:200px;height:200px;"/>
                        </a>
                    </div>
                    <div class="panel-footer">
                        {% if p.comment %}
                            {{ p.comment }}
                        {% else %}
                            <a href="{% url "photo-update" p.id %}">edit comments</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock maincontent %}

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %} /album {% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>A</b>lb{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Album</b>{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'auth_password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}/accounts{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

            {% block nav_links %}
                <li>
                    <a href="{% url "category-list" %}">
                        <i class="fa fa-dashboard"></i> <span>Category</span>
                    </a>
                </li>
                <li>
                        <a href="{% url "photo-list" %}">
                            <i class="fa fa-photo"></i> <span>Photo</span>
                        </a>
                    </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Update</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url "category-create" %}">
                                <i class="fa fa-contao"></i> Category
                            </a>
                        </li>
                        <li>
                                <a href="{% url "photo-create" %}">
                                    <i class="fa fa-photo"></i> Photo
                                </a>
                            </li>
                    </ul>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>

templates/base.html
{% extends 'adminlte/base.html' %}

{% block title %}Album{% endblock %}

{% block content %}
   

    <div class="container">
        {% block section %}
        {% endblock section %}
    </div>
    <div class="container">
        {% block maincontent %}
        {% endblock maincontent %}
    </div>
  
{% endblock %}